Fixed bug

diff --git a/summarize b/summarize
--- a/summarize
+++ b/summarize
@@ -1,6 +1,6 @@
 #!/u/psy/bin/ksh
 #
-# $Id: summarize,v 0.8 2002-08-31 17:49:52 psy Exp $
+# $Id: summarize,v 0.9 2002-08-31 18:02:11 psy Exp $
 # ------------------------------------------------------------------------------
 #
 # Summarizes a document (the whole shebang)
@@ -92,8 +92,8 @@ do
     --\?)      echo "$USAGE"; exit 0    ;;
     -help)     echo "$USAGE"; exit 0    ;;
     --help)    echo "$USAGE"; exit 0    ;;
-    -version)  echo '$Id: summarize,v 0.8 2002-08-31 17:49:52 psy Exp $'; exit 0    ;;
-    --version) echo '$Id: summarize,v 0.8 2002-08-31 17:49:52 psy Exp $'; exit 0    ;;
+    -version)  echo '$Id: summarize,v 0.9 2002-08-31 18:02:11 psy Exp $'; exit 0    ;;
+    --version) echo '$Id: summarize,v 0.9 2002-08-31 18:02:11 psy Exp $'; exit 0    ;;
     -*)        echo "$ME: invalid argument \"$1\""; exit 1 ;;
     *)         if [ -n "$CORPUS" ]
 	       then
@@ -120,10 +120,13 @@ then
 fi
 
 # Make sure number of factors is reasonable
-if [ $NUMFACTORS -lt 3 ]
+if [ -n "$NUMFACTORS" ]
 then
-    echo "$ME: can't have less than 3 factors"
-    exit 1
+    if [ $NUMFACTORS -lt 3 ]
+    then
+	echo "$ME: can't have less than 3 factors"
+	exit 1
+    fi
 fi
 
 # Clean up
@@ -141,7 +144,7 @@ fi
 
 # Write log file so we remember which options we used
 echo "------------------------------------------------------------------------
-Running "'$Id: summarize,v 0.8 2002-08-31 17:49:52 psy Exp $'"
+Running "'$Id: summarize,v 0.9 2002-08-31 18:02:11 psy Exp $'"
 Command line options: $ORIGOPTS
 Start time: `date`" \
     | tee -a $CORPUS.log
